class AudioPlaylist{constructor(paths){this.tracks=[];paths.forEach(path=>{this.tracks.push(new Audio("assets/sounds/"+path));});}
play(){let index=Math.floor(Math.random()*this.tracks.length);this.tracks[index].play();}}
class AudioLibrary{constructor(pathsSuccess,pathsError,pathsEnd,pathsPb){this.success=new AudioPlaylist(pathsSuccess);this.error=new AudioPlaylist(pathsError);this.end=new AudioPlaylist(pathsEnd);this.pb=new AudioPlaylist(pathsPb);}}
const DEFAULT_AUDIO_LIBRARY=new AudioLibrary(["success.mp3"],["error.mp3"],["end.mp3"],["pb.mp3"]);class Config{constructor(storage){this.storage=storage;let checkpoint=storage.getConfig();if(checkpoint==null){this.maxAttempts=3;this.displayAutocomplete=true;this.showCorrectAnswer=true;this.showBorders=true;this.askAgain=true;this.keepTrace=true;}else{this.maxAttempts=checkpoint.maxAttempts;this.displayAutocomplete=checkpoint.displayAutocomplete;this.showCorrectAnswer=checkpoint.showCorrectAnswer;this.showBorders=checkpoint.showBorders;this.askAgain=checkpoint.askAgain;this.keepTrace=checkpoint.keepTrace;}
this.library=DEFAULT_AUDIO_LIBRARY;}
fromDom(){this.maxAttempts=document.getElementById("input-config-maxAttempts").value;this.displayAutocomplete=document.getElementById("input-config-displayAutocomplete").checked;this.showCorrectAnswer=document.getElementById("input-config-showCorrectAnswer").checked;this.showBorders=document.getElementById("input-config-showBorders").checked;this.askAgain=document.getElementById("input-config-askAgain").checked;this.keepTrace=document.getElementById("input-config-keepTrace").checked;this.storage.saveConfig({maxAttempts:this.maxAttempts,displayAutocomplete:this.displayAutocomplete,showCorrectAnswer:this.showCorrectAnswer,showBorders:this.showBorders,askAgain:this.askAgain,keepTrace:this.keepTrace,});if(GLOBAL_QUIZ!=null){GLOBAL_QUIZ.notifyConfigChange();}}
toDom(){console.log("Using GLOBAL_CONFIG to set input values");document.getElementById("input-config-maxAttempts").value=this.maxAttempts;document.getElementById("input-config-displayAutocomplete").checked=this.displayAutocomplete;document.getElementById("input-config-showCorrectAnswer").checked=this.showCorrectAnswer;document.getElementById("input-config-showBorders").checked=this.showBorders;document.getElementById("input-config-askAgain").checked=this.askAgain;document.getElementById("input-config-keepTrace").checked=this.keepTrace;this.checkCurrentSettings();}
loadModeEasy(){this.maxAttempts=3;this.displayAutocomplete=true;this.showCorrectAnswer=true;this.showBorders=true;this.askAgain=true;this.keepTrace=true;this.toDom();}
loadModeMedium(){this.maxAttempts=1;this.displayAutocomplete=true;this.showCorrectAnswer=true;this.showBorders=true;this.askAgain=true;this.keepTrace=false;this.toDom();}
loadModeTest(){this.maxAttempts=1;this.displayAutocomplete=false;this.showCorrectAnswer=false;this.showBorders=false;this.askAgain=false;this.keepTrace=false;this.toDom();}
isInTestMode(){return this.maxAttempts==1&&!this.displayAutocomplete&&!this.showCorrectAnswer&&!this.showBorders&&!this.askAgain&&!this.keepTrace;}
isInMediumMode(){return this.maxAttempts==1&&this.displayAutocomplete&&this.showCorrectAnswer&&this.showBorders&&this.askAgain&&!this.keepTrace;}
isInEasyMode(){return this.maxAttempts==3&&this.displayAutocomplete&&this.showCorrectAnswer&&this.showBorders&&this.askAgain&&this.keepTrace;}
checkCurrentSettings(){this.fromDom();if(this.isInTestMode()){console.log("Checked current settings: we're in TEST mode");document.getElementById("btn-load-config-easy").classList.remove("btn-primary");document.getElementById("btn-load-config-medium").classList.remove("btn-primary");document.getElementById("btn-load-config-test").classList.add("btn-primary");}else if(this.isInMediumMode()){console.log("Checked current settings: we're in MEDIUM mode");document.getElementById("btn-load-config-easy").classList.remove("btn-primary");document.getElementById("btn-load-config-medium").classList.add("btn-primary");document.getElementById("btn-load-config-test").classList.remove("btn-primary");}else if(this.isInEasyMode()){console.log("Checked current settings: we're in EASY mode");document.getElementById("btn-load-config-easy").classList.add("btn-primary");document.getElementById("btn-load-config-medium").classList.remove("btn-primary");document.getElementById("btn-load-config-test").classList.remove("btn-primary");}else{console.log("Checked current settings: we're in NONE mode");document.getElementById("btn-load-config-easy").classList.remove("btn-primary");document.getElementById("btn-load-config-medium").classList.remove("btn-primary");document.getElementById("btn-load-config-test").classList.remove("btn-primary");}}
bindOnChangeEvents(){let self=this;["input-config-maxAttempts","input-config-displayAutocomplete","input-config-showCorrectAnswer","input-config-showBorders","input-config-askAgain","input-config-keepTrace"].forEach(query=>{document.getElementById(query).addEventListener("input",()=>{self.checkCurrentSettings();});});}}
const GLOBAL_CONFIG=new Config(GLOBAL_STORAGE);function runComparator(a,b){if(a.rating==b.rating){return b.time-a.time;}else{return a.rating-b.rating;}}
class QuizHistory{constructor(quizId){this.id=quizId;this.runs=[];this.attempts=0;}
fromString(string){if(string!=null){let parsed=JSON.parse(string);this.id=parsed.id;this.runs=parsed.runs;this.attempts=parsed.attempts;}
return this;}
toString(){return JSON.stringify({id:this.id,runs:this.runs,attempts:this.attempts});}
addRun(runDate,runRating,runTime){this.runs.push({date:runDate,rating:runRating,time:runTime});this.attempts++;}
getBestRun(){return getArrayMax(this.runs,runComparator);}}
function inflateBestRun(run){let element=importTemplate("template-best-run");if(run){element.querySelector(".run-rating").innerHTML=Math.floor(100*run.rating)+"<small>%</small>";element.querySelector(".run-time").innerHTML=formatTimeRun(run.time);element.querySelector(".run").classList.add("rating-rated");}else{element.querySelector(".run").classList.add("rating-none");}
return element;}const URL_INDEX="/data/index.json";function onBtnClearHistory(){if(window.confirm("Voulez-vous supprimer l'historique de tous les quizs ?")){GLOBAL_STORAGE.clearAllHistories();document.location.reload();}}
var QUIZ_IS_OFFICIAL=false;function onWindowLoad(){console.log("DOM is loaded");createMenu();document.getElementById("btn-open-config").addEventListener("click",()=>{GLOBAL_CONFIG.toDom();showModal("modal-config");});document.getElementById("form-signal").addEventListener("submit",(event)=>{event.preventDefault();let data={type:"report",quiz:event.target.querySelector("input[name='quizId']").value,question:event.target.querySelector("input[name='questionId']").value,reason:event.target.querySelector("select[name='reason']").value,comment:event.target.querySelector("textarea[name='comment']").value}
let request=new XMLHttpRequest();request.onreadystatechange=function(){if(request.readyState===4){if(request.status==200){alert("Merci pour votre retour !");}else{alert("Une erreur s'est produite. Veuillez réessayer ultérieurement.");}}}
request.open("post","https://cuiz.chalier.fr/api.php");request.send(JSON.stringify(data));closeModal("modal-signal");event.target.reset();});document.getElementById("btn-clear-history").addEventListener("click",onBtnClearHistory);document.getElementById("form-upload-json").addEventListener("submit",(event)=>{event.preventDefault();QUIZ_IS_OFFICIAL=false;let url=event.target.querySelector("input[name='upload-json-url']").value;if(url){loadQuizFromUrl(url);}else{let file=event.target.querySelector("input[name='upload-json-file']").files[0];if(file){let reader=new FileReader();reader.onload=function(event){let data=JSON.parse(event.target.result);loadQuizData(data);}
reader.readAsText(file,"UTF-8");}}
closeModal("modal-upload-json");event.target.reset();});document.getElementById("btn-make-suggestion").addEventListener("click",()=>{let modal=document.getElementById("modal-signal");modal.querySelector("form").reset();modal.querySelector("option[value='suggestion']").selected=true;modal.classList.add("active");});GLOBAL_CONFIG.bindOnChangeEvents();document.getElementById("input-search-quiz").addEventListener("input",(event)=>{let query=normalizeTurbo(event.target.value);if(query){document.querySelectorAll(".grid-item").forEach(item=>{let filters=item.getAttribute("filter").split(";");let matches=false;for(let i=0;i<filters.length;i++){if(query.includes(filters[i])||filters[i].includes(query)){matches=true;hasAny=true;break;}}
if(matches){item.classList.remove("hidden");}else{item.classList.add("hidden");}});}else{document.querySelectorAll(".grid-item").forEach(item=>{item.classList.remove("hidden");});}
MASONRIES.forEach(m=>{m.layout();});});}
function onMenuItemClick(quiz){console.log("Clicked on menu item",quiz.id,"entitled \""+quiz.title+"\"");loadQuizFromUrl(quiz.dataset);QUIZ_IS_OFFICIAL=true;}let THUMBNAILS_TO_LOAD=0;let MASONRIES=[];function createMenu(){console.log("Creating menu");sendRequest(URL_INDEX,(response)=>{THUMBNAILS_TO_LOAD=0;let data=JSON.parse(response);if(getUrlParameters().has("quiz")){let quizId=parseInt(getUrlParameters().get("quiz"));for(let i=0;i<data.quizzes.length;i++){if(data.quizzes[i].id==quizId){onMenuItemClick(data.quizzes[i]);return;}}}
data.quizzes.sort((a,b)=>{if(a.category!=b.category){let i=data.categories.indexOf(a.category);let j=data.categories.indexOf(b.category);return i-j;}else{return a.id-b.id;}});let container=document.getElementById("main-container");container.innerHTML="";let menu=importTemplate("template-menu");data.quizzes.forEach(quiz=>{menu.querySelector(".quiz-menu").appendChild(createMenuItem(quiz));});container.appendChild(menu);});}
function createMenuItem(quiz){let element=importTemplate("template-menu-item");element.querySelector(".quiz-title").textContent=quiz.title;element.querySelector(".quiz-category").textContent=quiz.category;element.querySelector("div").setAttribute("filter",normalizeTurbo(quiz.category)+";"+normalizeTurbo(quiz.title)+";"+quiz.id);let thumbnail=element.querySelector(".quiz-thumbnail");if(quiz.thumbnail!=null){THUMBNAILS_TO_LOAD++;thumbnail.addEventListener("load",onThumbnailLoadCallback);thumbnail.src=quiz.thumbnail;}else{thumbnail.parentNode.parentNode.removeChild(thumbnail.parentNode);}
let history=GLOBAL_STORAGE.getHistory(quiz.id);element.querySelector(".quiz-pb").appendChild(inflateBestRun(history.getBestRun()));element.querySelector("div").addEventListener("click",()=>{onMenuItemClick(quiz);});return element;}
function onThumbnailLoadCallback(){THUMBNAILS_TO_LOAD--;if(THUMBNAILS_TO_LOAD==0){console.log("All thumbnails are loaded, initializing Masonry");MASONRIES=[];document.querySelectorAll(".grid").forEach(grid=>{MASONRIES.push(new Masonry(grid,{gutter:".gutter-sizer",columnWidth:".grid-sizer",itemSelector:".grid-item",percentPosition:true}));});}}function startChronometer(container){container.innerHTML="0:00";let timeStart=new Date();QUIZ_TIME_INTERVAL=setInterval(function(){let elapsed=((new Date())-timeStart)/1000;let minutes=Math.floor(elapsed/60);let seconds=parseInt(elapsed-60*minutes);container.textContent=minutes.toString()+":"+seconds.toString().padStart(2,"0");},100);}
function animateIcon(path,target,colorClass){let animForward=document.getElementById(target);let animBackward=document.getElementById("animToTag");path.classList.add(colorClass);animForward.beginElement();setTimeout(()=>{animBackward.beginElement();path.classList.remove(colorClass);},1000);}
function sendRequest(url,callback){let request=new XMLHttpRequest();request.onreadystatechange=function(){if(request.readyState===4&&request.status===200){console.log("Received response from",url);if(callback!=null){callback(request.responseText);}}else if(request.readyState===4){console.log("Fetching",url,"raised an error:",request.status);}}
console.log("Sending request to",url);request.open("get",url,true);request.send(null);}
function toggleCollapsible(element){if(element.style.maxHeight){element.style.maxHeight=null;}else{element.style.maxHeight=Math.max(154,element.scrollHeight)+"px";}}
function formatTimeRun(ms){let minutes=Math.floor(ms/60000);let seconds=Math.floor(ms/1000)-60*minutes;let tenths=Math.floor((ms-60000*minutes-1000*seconds)/100);return minutes+"<small>:</small>"+seconds.toString().padStart(2,"0")+"<small>."+tenths+"</small>";}
function formatTimePrecise(ms){let seconds=Math.floor(ms/1000);let remaining=Math.floor(ms-1000*seconds);return seconds+"."+remaining.toString().padStart(3,"0");}
class Confetti{constructor(COLORS){this.style=COLORS[~~range(0,5)];this.rgb=`rgba(${this.style[0]},${this.style[1]},${this.style[2]}`;this.r=~~range(2,6);this.r2=2*this.r;this.replace();}
replace(){this.opacity=0;this.dop=0.03*range(1,4);this.x=range(-this.r2,w-this.r2);this.y=range(-20,h-this.r2);this.xmax=w-this.r;this.ymax=h-this.r;this.vx=range(0,2)+8*0.5-5;return this.vy=0.7*this.r+range(-1,1);}
draw(context){var ref;this.x+=this.vx;this.y+=this.vy;this.opacity+=this.dop;if(this.opacity>1){this.opacity=1;this.dop*=-1;}
if(this.opacity<0||this.y>this.ymax){this.replace();}
if(!((0<(ref=this.x)&&ref<this.xmax))){this.x=(this.x+this.xmax)%this.xmax;}
return drawCanvasCircle(context,~~this.x,~~this.y,this.r,`${this.rgb},${this.opacity})`);}};function range(a,b){return(b-a)*Math.random()+a;};function drawCanvasCircle(context,x,y,r,style){context.beginPath();context.arc(x,y,r,0,2*Math.PI,false);context.fillStyle=style;return context.fill();};function startConfettiAnimation(duration){console.log("Starting confetti animation");let canvas=document.createElement("canvas");let container=document.getElementById("confetti-container")
container.appendChild(canvas);container.style.opacity=1;container.classList.add("active");let requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;let cancelAnimationFrame=window.cancelAnimationFrame||window.mozCancelAnimationFrame;let animationFrameRequestId;let confetti,i;let NUM_CONFETTI=350;let COLORS=[[53,53,105],[32,32,64],[87,85,217],[121,119,221],[66,64,212]];let context=canvas.getContext("2d");window.w=canvas.width=window.innerWidth;window.h=canvas.height=window.innerHeight;confetti=(function(){var j,ref,results;results=[];for(i=j=1,ref=NUM_CONFETTI;(1<=ref?j<=ref:j>=ref);i=1<=ref?++j:--j){results.push(new Confetti(COLORS));}
return results;})();function step(){var c,j,len,results;animationFrameRequestId=requestAnimationFrame(step);context.clearRect(0,0,w,h);results=[];for(j=0,len=confetti.length;j<len;j++){c=confetti[j];results.push(c.draw(context));}
return results;};animationFrameRequestId=requestAnimationFrame(step);setTimeout(()=>{container.style.opacity=0;setTimeout(()=>{cancelAnimationFrame(animationFrameRequestId);container.innerHTML="";container.classList.remove("active");container.style.opacity=1;},1000);},duration);}
const MAP_TILE_PROVIDER="https://a.basemaps.cartocdn.com/rastertiles/dark_nolabels/{z}/{x}/{y}@2x.png";class QuizInput{constructor(config,data,quiz){this.config=config;this.data=data;this.quiz=quiz;this.container=null;}
inflate(container){throw new Error("Not implemented!");}
clear(){throw new Error("Not implemented!");}
giveFeedback(polarity){throw new Error("Not implemented!");}
showCorrectAnswer(index){throw new Error("Not implemented!");}
evaluate(index){throw new Error("Not implemented!");}}
class QuizInputText extends QuizInput{constructor(config,data,quiz){super(config,data,quiz);this.dom={input:null,autocomplete:null,icon:null,form:null}
this.candidates=[];data.questions.forEach(question=>{if(!this.candidates.includes(question.answer)){this.candidates.push(question.answer);}});this.candidates.sort();this.disabled=false;}
gatherSuggestions(prefix){let suggestions=[];this.candidates.forEach(candidate=>{if(normalize(candidate).startsWith(prefix)){suggestions.push(candidate);}});return suggestions;}
inflateAutoComplete(suggestions){let self=this;this.dom.autocomplete.innerHTML="";suggestions.forEach(suggestion=>{let span=document.createElement("span");span.className="label label-rounded text-small";span.textContent=suggestion;span.addEventListener("click",(event)=>{self.dom.input.value=suggestion;self.quiz.submit();});this.dom.autocomplete.appendChild(span);});}
inflate(container){this.disabled=false;this.container=container;container.innerHTML="";let element=importTemplate("template-input-"+this.data.input);let self=this;element.querySelector("form").addEventListener("submit",(event)=>{event.preventDefault();if(!self.disabled){self.quiz.submit();}});this.dom.input=element.querySelector("input.form-input");this.dom.icon=element.querySelector("svg path");this.dom.form=element.querySelector("form");this.dom.autocomplete=element.querySelector(".autocomplete");this.dom.input.addEventListener("input",()=>{let prefix=normalize(self.dom.input.value);let suggestions=[];if(prefix.length>0){suggestions=self.gatherSuggestions(prefix);}
if(self.config.displayAutocomplete){self.inflateAutoComplete(suggestions);}
if(suggestions.length==1&&prefix==normalize(suggestions[0])){self.quiz.submit();}});this.dom.input.addEventListener("keydown",(event)=>{if(event.keyCode==9){event.preventDefault();let prefix=normalize(self.dom.input.value);let suggestions=self.gatherSuggestions(prefix);if(suggestions.length==1){self.dom.input.value=suggestions[0];self.quiz.submit();}
self.dom.input.focus();}});element.querySelector(".answer-close").addEventListener("click",()=>{toggleCollapsible(self.container.querySelector(".answer"));self.disabled=false;this.container.querySelector("fieldset").disabled=false;self.quiz.next();});container.appendChild(element);}
evaluate(index){console.log("Evaluating text input: value is \""+this.dom.input.value+"\" while answer is \""+this.data.questions[index].answer+"\"");let proposition=normalize(this.dom.input.value);if(normalize(this.data.questions[index].answer)==proposition){return true;}
for(let i=index+1;i<this.data.size;i++){if(this.data.questions[i].prompt==this.data.questions[index].prompt&&normalize(this.data.questions[i].answer)==proposition){let aux=this.data.questions[i];this.data.questions[i]=this.data.questions[index];this.data.questions[index]=aux;return true;}}
return false;}
clear(){this.dom.form.reset();this.dom.input.focus();this.dom.autocomplete.innerHTML="";}
giveFeedback(polarity){if(polarity){animateIcon(this.dom.icon,"animToCheck","path-success");}else{animateIcon(this.dom.icon,"animToCross","path-error");}}
showCorrectAnswer(index){this.clear();this.container.querySelector("fieldset").disabled=true;this.disabled=true;let container=this.container.querySelector(".answer");toggleCollapsible(container);container.querySelector(".answer-value").textContent=this.data.questions[index].answer;if(this.data.questions[index].tips!=null){container.querySelector(".answer-tips").innerHTML=this.data.questions[index].tips;}else{container.querySelector(".answer-tips").textContent="Aucune indication renseignée pour cette question.";}
container.querySelector("button").focus();}}
const FEATURE_STATE_OFF=0;const FEATURE_STATE_SUCCESS=1;const FEATURE_STATE_ERROR=2;const FEATURE_STATE_HIGHLIGHT=3;class QuizInputMap extends QuizInput{constructor(config,data,quiz){super(config,data,quiz);this.map=null;this.bounds=null;this.features={};this.states={};this.selection=null;this.disabled=false;let request=new XMLHttpRequest();request.open("get",this.data.settings.source,false);request.send();this.polygons=JSON.parse(request.responseText);}
inflate(container){container.innerHTML="";container.appendChild(importTemplate("template-input-map"));this.map=L.map(container.querySelector(".input-map"),{center:[0,0],zoom:2,maxBounds:this.polygons.maxBounds});L.tileLayer(MAP_TILE_PROVIDER,{noWrap:true,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',}).addTo(this.map);let stroke=null;if(this.config.showBorders){stroke="#4240d4";}
let self=this;let featureIdSelection=[];this.data.questions.forEach(question=>{featureIdSelection.push(question.answer);});for(let featureId in this.polygons.polys){let feature=L.geoJson(this.polygons.polys[featureId],{style:{weight:1,stroke:stroke,fillOpacity:0,color:"#4240d4",},onEachFeature:(_,layer)=>{layer.on({click:_=>{self.handleClick(featureId);},});},})
feature.addTo(this.map);if(featureIdSelection.includes(featureId)){if(this.bounds==null){this.bounds=feature.getBounds();}else{this.bounds.extend(feature.getBounds());}}
this.features[featureId]=feature;this.states[featureId]=FEATURE_STATE_OFF;}
console.log("Map boundaries:",this.bounds);setTimeout(()=>{this.map.invalidateSize();this.map.fitBounds(this.bounds);},10);}
clear(){this.selection=null;}
handleClick(featureId){if(!this.disabled){this.selection=featureId;this.quiz.submit();}}
evaluate(index){console.log("Selected feature is",this.selection);return this.data.questions[index].answer==this.selection;}
setFeatureStyle(featureId,state=null){if(state==null){state=this.states[featureId];}
if(state==FEATURE_STATE_OFF){this.features[featureId].setStyle({color:"#4240d4",fillOpacity:0,});}else if(state==FEATURE_STATE_SUCCESS){this.features[featureId].setStyle({color:"#32b643",fillOpacity:0.5,});}else if(state==FEATURE_STATE_ERROR){this.features[featureId].setStyle({color:"crimson",fillOpacity:0.5,});}else if(state==FEATURE_STATE_HIGHLIGHT){this.features[featureId].setStyle({color:"#b65a32",fillOpacity:0.5});}}
giveFeedback(polarity,willReoccur){let polarityState=polarity?FEATURE_STATE_SUCCESS:FEATURE_STATE_ERROR;if(this.config.keepTrace&&!willReoccur){if(polarity){this.states[this.selection]=FEATURE_STATE_SUCCESS;}}
let featureId=this.selection;this.setFeatureStyle(featureId,polarityState);setTimeout(()=>{this.setFeatureStyle(featureId);},500);}
showCorrectAnswer(index){let featureId=this.data.questions[index].answer;this.setFeatureStyle(featureId,FEATURE_STATE_HIGHLIGHT);if(!this.config.askAgain&&this.config.keepTrace){this.states[featureId]=FEATURE_STATE_ERROR;}
let marker=L.marker(this.features[featureId].getBounds().getCenter()).addTo(this.map).bindTooltip(this.data.questions[index].label+" &times;").openTooltip();let self=this;this.disabled=true;marker.on("click",()=>{this.setFeatureStyle(featureId);self.map.removeLayer(marker);self.disabled=false;self.quiz.next();});}}
const FONTS=["Arial","Verdana","Helvetica","Tahoma","Trebuchet MS","Times New Roman","Georgia","Garamond","Courier New","Brush Script MT"];class QuizPrompt{constructor(config,data){this.config=config;this.data=data;this.container=null;}
inflate(container){this.container=container;container.innerHTML="";}
load(index){throw new Error("Not implemented!");}
searchForPreviousAnswers(index){let previousAnswers=[];for(let i=0;i<index;i++){if(this.data.questions[index].prompt==this.data.questions[i].prompt){previousAnswers.push(this.data.questions[i].answer);}}
return previousAnswers;}
displayPreviousAnswers(index){let previousAnswers=this.searchForPreviousAnswers(index);let wrapper=this.container.querySelector(".prompt-previous-answers");wrapper.classList.add("hidden");let container=this.container.querySelector(".prompt-previous-answers-list");container.innerHTML="";if(previousAnswers.length>0){wrapper.classList.remove("hidden");previousAnswers.forEach(answer=>{let span=document.createElement("span");span.className="label";span.textContent=answer;container.appendChild(span);});}}}
class QuizPromptImage extends QuizPrompt{inflate(container){QuizPrompt.prototype.inflate.call(this,container);this.container.appendChild(importTemplate("template-prompt-image"));}
load(index){this.container.querySelector(".prompt-image").src=this.data.questions[index].prompt;if(index<this.data.size-1){let image=new Image();image.src=this.data.questions[index+1].prompt;}
this.displayPreviousAnswers(index);}}
class QuizPromptText extends QuizPrompt{inflate(container){QuizPrompt.prototype.inflate.call(this,container);this.container.appendChild(importTemplate("template-prompt-text"));}
load(index){this.container.querySelector(".prompt-text").textContent=this.data.questions[index].prompt;this.displayPreviousAnswers(index);}}
class QuizPromptSentence extends QuizPrompt{constructor(config,data){super(config,data);let request=new XMLHttpRequest();request.open("get",data.settings.source,false);request.send();this.sentences=JSON.parse(request.responseText)
this.currentIndex=null;}
inflate(container){QuizPrompt.prototype.inflate.call(this,container);let element=importTemplate("template-prompt-sentence");let self=this;element.querySelector("button.another-sentence").addEventListener("click",()=>{if(self.currentIndex!=null){self.load(self.currentIndex);}
let possibleInput=self.container.nextElementSibling.querySelector("input");if(possibleInput!=null){possibleInput.focus();}});this.container.appendChild(element);}
load(index){this.currentIndex=index;let self=this;if(this.sentences==null){console.log("Sentences are not loaded, retrying in a bit…");setTimeout(()=>{self.load(index);},100);}else{let element=this.container.querySelector(".prompt-sentence");element.textContent=choose(this.sentences[this.data.questions[index].prompt]);element.style.fontFamily=choose(FONTS);}}}var QUIZ_TIME_INTERVAL=null;var GLOBAL_QUIZ=null;function loadQuizData(data){let container=document.getElementById("main-container");GLOBAL_QUIZ=new Quiz(GLOBAL_CONFIG,data);GLOBAL_QUIZ.inflate(container);GLOBAL_QUIZ.start();}
function loadQuizFromUrl(datasetUrl){sendRequest(datasetUrl,(response)=>{loadQuizData(JSON.parse(response))});}
function questionStatsComparator(a,b){if(a.success&&!b.success){return 1;}else if(!a.success&&b.success){return-1;}else{if(a.attempts==b.attempts){return a.time-b.time;}else{return a.attempts-b.attempts;}}}
class Quiz{constructor(config,data){console.log("Constructing quiz",data.id);this.config=config;this.data=data;this.container=null;this.prompt=null;if(data.prompt=="image"){this.prompt=new QuizPromptImage(config,data);}else if(data.prompt=="text"){this.prompt=new QuizPromptText(config,data);}else if(data.prompt=="sentence"){this.prompt=new QuizPromptSentence(config,data);}else{throw new Error("Invalid quiz prompt: "+data.prompt);}
this.input=null;if(data.input=="text"){this.input=new QuizInputText(config,data,this);}else if(data.input=="map"){this.input=new QuizInputMap(config,data,this);}else{throw new Error("Invalid quiz input:"+data.input);}
this.index=-1;this.consecutiveAttempts=0;this.monitoring={success:0,errors:0,timeStart:null,validTest:this.config.isInTestMode(),details:[],timeQuestionStart:null}
this.finished=false;}
getQuestion(questionId){for(let i=0;i<this.data.questions.length;i++){if(this.data.questions[i].id==questionId){return this.data.questions[i];}}
return null;}
inflate(container){console.log("Inflating quiz",this.data.id,"within",container);this.container=container;container.innerHTML="";let element=importTemplate("template-quiz");element.querySelector(".quiz-header .quiz-category").textContent=this.data.category;element.querySelector(".quiz-header .quiz-title").textContent=this.data.title;element.querySelector(".quiz-header .quiz-progress-bar").max=this.data.size;element.querySelector(".quiz-id").textContent=this.data.id;this.prompt.inflate(element.querySelector(".quiz-prompt"));let self=this;element.querySelector(".btn-signal").addEventListener("click",()=>{let modal=document.getElementById("modal-signal");modal.querySelector("form").reset();modal.querySelector("input[name='quizId']").value=self.data.id;modal.querySelector("input[name='questionId']").value=self.data.questions[self.index].id;modal.querySelector("option[value='promptWrong']").selected=true;modal.classList.add("active");});element.querySelector(".btn-restart").addEventListener("click",()=>{self.start();});element.querySelector(".btn-terminate").addEventListener("click",()=>{self.terminate();});container.appendChild(element);}
start(){this.input.inflate(this.container.querySelector(".quiz-input"));this.index=-1;this.monitoring.success=0;this.monitoring.errors=0;this.monitoring.timeStart=new Date();if(QUIZ_TIME_INTERVAL!=null){clearInterval(QUIZ_TIME_INTERVAL);}
startChronometer(this.container.querySelector(".quiz-time"));this.monitoring.validTest=true;this.checkForTestMode();this.monitoring.timeQuestionStart=null;this.monitoring.details=[];this.validTest=this.config.isInTestMode();let seed=(new Date()).toString();let params=getUrlParameters();if(params.has("seed")){seed=params.get("seed");}
this.finished=false;this.shuffle(seed);this.next();}
shuffle(seed){console.log("Shuffling using seed",seed);let randomGenerator=new Math.seedrandom(seed);this.data.questions.sort((a,b)=>{return a.id-b.id;});this.data.questions.sort(_=>randomGenerator()-0.5);}
next(){this.index++;this.input.clear();this.container.querySelector(".quiz-progress-bar").value=this.index;let score=this.monitoring.success+this.monitoring.errors>0?this.monitoring.success/(this.monitoring.success+this.monitoring.errors):1;this.container.querySelector(".quiz-score").textContent=parseInt(100*score)+"%";this.consecutiveAttempts=0;if(this.index>=this.data.size){this.finish();}else{console.log("Loading question at index",this.index,"id:",this.data.questions[this.index].id);this.prompt.load(this.index);this.container.querySelector(".question-id").textContent=this.data.questions[this.index].id;this.container.querySelector(".quiz-tries").textContent=this.config.maxAttempts>1?this.config.maxAttempts+" essais restants":this.config.maxAttempts+" essai restant";this.monitoring.details.push({id:this.data.questions[this.index].id,attempts:0,time:null,success:false});this.monitoring.timeQuestionStart=new Date();}}
success(){console.log("Question is a success!");this.monitoring.success++;this.monitoring.details[this.monitoring.details.length-1].success=true;this.monitoring.details[this.monitoring.details.length-1].time=(new Date())-this.monitoring.timeQuestionStart;this.config.library.success.play();this.input.giveFeedback(true,false);this.next();}
error(){console.log("Question is a failure…");let currentQuestion=this.data.questions[this.index];this.consecutiveAttempts++;this.monitoring.details[this.monitoring.details.length-1].success=false;this.monitoring.details[this.monitoring.details.length-1].time=(new Date())-this.monitoring.timeQuestionStart;this.config.library.error.play();this.input.giveFeedback(false,this.consecutiveAttempts<this.config.maxAttempts||this.config.askAgain);if(this.consecutiveAttempts>=this.config.maxAttempts){this.monitoring.errors++;if(this.config.askAgain){this.data.questions.splice(this.index,1);this.data.questions.push(currentQuestion);this.index--;}
if(this.config.showCorrectAnswer){if(this.config.askAgain){this.input.showCorrectAnswer(this.data.size-1);}else{this.input.showCorrectAnswer(this.index);}}else{this.next();}}else{this.input.clear();}}
notifyConfigChange(){if(!this.finished){this.start();}}
checkForTestMode(){this.monitoring.validTest=this.monitoring.validTest&&this.config.isInTestMode()&&!getUrlParameters().has("seed")&&QUIZ_IS_OFFICIAL;if(this.monitoring.validTest){this.container.querySelector(".quiz-test-on").classList.remove("hidden");this.container.querySelector(".quiz-test-off").classList.add("hidden");}else{this.container.querySelector(".quiz-test-off").classList.remove("hidden");this.container.querySelector(".quiz-test-on").classList.add("hidden");}}
submit(){this.checkForTestMode();console.log("Submitting answer for quiz",this.data.id,"- test mode is",this.monitoring.validTest);if(this.index<this.data.size){this.monitoring.details[this.index].attempts++;if(this.input.evaluate(this.index)){this.success();}else{let remainingAttempts=this.config.maxAttempts-this.consecutiveAttempts;this.container.querySelector(".quiz-tries").textContent=remainingAttempts>1?remainingAttempts+" essais restants":remainingAttempts+" essai restant";this.error();}}}
terminate(){this.monitoring.validTest=false;while(this.index<this.data.size){this.monitoring.errors++;this.index++;}
this.finish();}
getCurrentRunSummary(){this.checkForTestMode();let data={rating:this.monitoring.success/(this.monitoring.success+this.monitoring.errors),time:(new Date())-this.monitoring.timeStart,totalAttempts:0,validTest:this.monitoring.validTest,fastestAnswer:null,slowestAnswer:null}
this.monitoring.details.forEach(detail=>{data.totalAttempts+=detail.attempts;if(data.fastestAnswer==null||detail.time<data.fastestAnswer.time){data.fastestAnswer=detail;}
if(data.slowestAnswer==null||detail.time>data.slowestAnswer.time){data.slowestAnswer=detail;}});return data;}
finish(){this.finished=true;console.log("Quiz just finished!");clearInterval(QUIZ_TIME_INTERVAL);let summary=this.getCurrentRunSummary();let history=GLOBAL_STORAGE.getHistory(this.data.id);let isPb=false;if(summary.validTest){isPb=true;let previousPb=history.getBestRun();if(previousPb!=null){isPb=runComparator({rating:summary.rating,time:summary.time},previousPb)>0;}
GLOBAL_STORAGE.saveRun(this.data.id,summary.rating,summary.time);}else{GLOBAL_STORAGE.countRun(this.data.id);}
if(isPb){this.config.library.pb.play();startConfettiAnimation(10000);}else{this.config.library.end.play();}
this.inflateQuizEnd(history,summary,isPb);}
inflateQuizEnd(history,summary,isPb){let element=importTemplate("template-quiz-end");element.querySelector(".quiz-title").innerHTML=this.data.category+" &ndash; "+this.data.title;this.inflateAnswers(element);const animDuration=1000;startCountingAnimation(element.querySelector(".quiz-rating"),parseInt(summary.rating*100),(x)=>parseInt(x),animDuration);startCountingAnimation(element.querySelector(".quiz-time"),summary.time,formatTimeRun,animDuration);if(history.attempts>1){element.querySelector(".quiz-attempts").textContent=history.attempts+" tentatives";}else{element.querySelector(".quiz-attempts").textContent=history.attempts+" tentative";}
if(isPb){element.querySelector(".quiz-pb").appendChild(inflateBestRun(summary));}else{element.querySelector(".quiz-pb").appendChild(inflateBestRun(history.getBestRun()));}
let self=this;element.querySelector(".button-restart").addEventListener("click",()=>{self.inflate(self.container);self.start();});if(isPb){element.querySelector(".quiz-new-record form").addEventListener("submit",(event)=>{event.preventDefault();self.shareRecord(summary,(success)=>{if(success){let target=event.target;let parent=target.parentNode;parent.removeChild(target);parent.querySelector("span").style.marginBottom="0";inflateLeaderboard(self.data.id,self.container.querySelector(".quiz-leaderboard"));}else{alert("Une erreur est survenue lors du partage du score. Veuillez réessayer ultérieurement.");}});});}else{let target=element.querySelector(".quiz-new-record");target.parentNode.removeChild(target);}
this.inflateHistory(element,history,summary,isPb)
this.container.innerHTML="";this.container.appendChild(element);inflateLeaderboard(this.data.id,this.container.querySelector(".quiz-leaderboard"));}
inflateHistory(element,history,summary,isPb){let points=[];history.runs.forEach(run=>{points.push({y:100*run.rating,x:run.time/1000})})
let ctx=element.getElementById("quiz-history-chart").getContext("2d");let chart=new Chart(ctx,{type:"scatter",data:{datasets:[{label:"Actuel",data:[{x:summary.time/1000,y:summary.rating*100}],borderColor:"#CCAB00",backgroundColor:"gold"},{label:"Évaluations",data:points,borderColor:"#3F3CCC",backgroundColor:"#4F4CFF"}]},options:{responsive:true,maintainAspectRatio:false,aspectRatio:1,legend:{display:false},scales:{yAxes:[{position:'left',ticks:{userCallback:function(value){return value+"%";},beginAtZero:true,max:100}}],xAxes:[{position:'bottom',scaleLabel:{display:true,labelString:"Temps (s)"}}]},tooltips:{callbacks:{label:function(tooltipItem,data){let point=data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index];let temp=document.createElement("div");if(tooltipItem.datasetIndex==1){temp.innerHTML=(new Date(history.runs[tooltipItem.index].date)).toLocaleDateString()+" &middot; ";}
temp.innerHTML+=Math.floor(point.y)+"% &middot; "+formatTimeRun(point.x*1000);return temp.textContent;}}}}});let self=this;element.querySelector(".btn-erase-quiz-history").addEventListener("click",()=>{if(confirm("Voulez-vous effacer l'historique local du quiz "+self.data.id+" ?")){GLOBAL_STORAGE.clearHistory(self.data.id);alert("L'historique local du quiz "+self.data.id+" a bien été supprimé.");}});}
inflateAnswers(container){let slowest;this.monitoring.details.forEach(detail=>{if(slowest==null||detail.time>slowest){slowest=detail.time;}});let table=container.querySelector("table");this.monitoring.details.forEach(detail=>{let tr=document.createElement("tr");let tdScore=document.createElement("td");if(detail.success){tdScore.innerHTML='<i class="icon icon-check text-success"></i>';}else{tdScore.innerHTML='<i class="icon icon-cross text-error"></i>';}
tr.appendChild(tdScore);let tdLabel=document.createElement("td");tdLabel.textContent=this.getQuestion(detail.id).label;tr.appendChild(tdLabel);let tdTime=document.createElement("td");let answerTime=importTemplate("template-answer-time");answerTime.querySelector(".answer-time-value").innerHTML=formatTimePrecise(detail.time);answerTime.querySelector(".answer-time-bar-filled").style.width=Math.floor(100*detail.time/slowest)+"%";tdTime.appendChild(answerTime);tr.appendChild(tdTime);table.appendChild(tr);});}
shareRecord(summary,callback){let name=event.target.querySelector("input").value.trim();if(name!=null&&name.length>0){let request=new XMLHttpRequest();request.onreadystatechange=function(){if(request.readyState===4){callback(request.status==200);}}
request.open("post","https://cuiz.chalier.fr/api.php");request.send(JSON.stringify({name:name,quiz:this.data.id,rating:summary.rating,time:summary.time,date:this.monitoring.timeStart,type:"record"}));}else{alert("Veuillez entrer un nom valide");}}}
function inflateLeaderboard(quizId,container){container.innerHTML="";container.appendChild(importTemplate("template-leaderboard"));sendRequest("https://cuiz.chalier.fr/api.php?id="+quizId,(response)=>{let table=container.querySelector("table");let rows=table.querySelectorAll("tr");for(let i=1;i<rows.length;i++){table.removeChild(rows[i]);}
let data=JSON.parse(response);if(data.length){data.sort(runComparator).reverse();let names={};let index=-1;data.forEach(row=>{if(!(row.name in names)&&index<20){names[row.name]=null;index++;let tr=document.createElement("tr");if(index==0){tr.innerHTML="<td><i class='icon icon-trophy'></i> "+(index+1)+"</td>";}else{tr.innerHTML="<td>"+(index+1)+"</td>";}
tr.innerHTML+="<td class='text-uppercase'>"+row.name+"</td>";tr.innerHTML+="<td>"+Math.floor(100*row.rating)+"<small>%</small></td>";tr.innerHTML+="<td>"+formatTimeRun(parseInt(row.time))+"</td>";tr.innerHTML+="<td><small>"+(new Date(row.date)).toLocaleDateString();+"</small></td>";if(index==0){tr.classList.add("rating-gold");}else if(index==1){tr.classList.add("rating-silver");}else if(index==2){tr.classList.add("rating-bronze");}
table.appendChild(tr);}});}else{container.innerHTML="Aucun score n'a été partagé.";}});}
function storageAvailable(type){console.log("Checking for storage",type);var storage;try{storage=window[type];var x="__storage_test__";storage.setItem(x,x);storage.removeItem(x);return true;}
catch(e){return e instanceof DOMException&&(e.code===22||e.code===1014||e.name==="QuotaExceededError"||e.name==="NS_ERROR_DOM_QUOTA_REACHED")&&(storage&&storage.length!==0);}}
class Storage{constructor(){this.available=storageAvailable("localStorage");if(this.available){console.log("Storage is available");}else{console.error("Storage is unavailable");}}
getConfig(){if(!this.available)return null;return JSON.parse(localStorage.getItem("config"));}
saveConfig(config){if(this.available){localStorage.setItem("config",JSON.stringify(config));}}
getHistory(quizId){if(!this.available)return null;return(new QuizHistory()).fromString(localStorage.getItem("quiz-"+quizId));}
saveRun(quizId,rating,time){console.log("Saving run for quiz id",quizId,"with rating",rating,"and time",time);if(this.available){let history=this.getHistory(quizId);history.addRun(new Date(),rating,time);localStorage.setItem("quiz-"+quizId,history.toString());}}
countRun(quizId){if(this.available){let history=this.getHistory(quizId);history.attempts++;localStorage.setItem("quiz-"+quizId,history.toString());}}
clearAllHistories(){if(this.available){let aux=localStorage.getItem("config");localStorage.clear();localStorage.setItem("config",aux);}}
clearHistory(quizId){if(this.available){localStorage.removeItem("quiz-"+quizId);}}}
const GLOBAL_STORAGE=new Storage();